"""Generate Sqpack/S11Opt/Data.lean: Trump's packing in Q(u0) and the 44 wall + 55 pair facts.

Every quantity is a polynomial of degree <= 7 in u0 with rational coefficients (reduced mod P).
Each fact `L <= R` is proved as `R - L = r + k*P` (exact polynomial identity, `linear_combination`)
with `r >= 0` on the isolating interval (`hIv`, kernel-checked); contacts have r = 0.
"""
import sys
from fractions import Fraction as F
from field import P, add, sub, mul, divmod_, red, trim, const, horner_iv, ev
from construct import build

DIGITS = 40


def rat(q):
    q = F(q)
    if q.denominator == 1:
        return f"({q.numerator} : ℝ)"
    return f"({q.numerator} / {q.denominator} : ℝ)"


def ratQ(q):
    q = F(q)
    if q.denominator == 1:
        return f"{q.numerator}"
    return f"{q.numerator}/{q.denominator}"


def plist(p):
    return "[" + ", ".join(rat(c) for c in p) + "]"


def qlist(p):
    return "[" + ", ".join(ratQ(c) for c in p) + "]"


def pexpr(p, x="u₀"):
    if not p:
        return "0"
    terms = []
    for i, c in enumerate(p):
        if c == 0:
            continue
        terms.append(rat(c) + ("" if i == 0 else (f" * {x}" if i == 1 else f" * {x} ^ {i}")))
    return "(" + " + ".join(terms) + ")"


def main(out):
    d = build()
    c, s, T, sqs = d['c'], d['s'], d['T'], d['sq']
    # isolating interval of width 10^-DIGITS
    from field import root_interval
    l0, h0 = root_interval(4 * DIGITS)
    scale = 10 ** DIGITS
    lo = F(int(l0 * scale), scale)
    hi = lo + F(1, scale)
    assert ev(P, lo) < 0 < ev(P, hi)

    L = []
    w = L.append
    w("import Sqpack.S11Opt.Basic\n")
    w("/-! Generated by `scripts/s11opt/gen.py` from Trump's packing (the author's pinned")
    w("`trump11/packing.py`, jlevy/squares c55726e).  Do not edit by hand. -/\n")
    w("namespace SquarePacking.S11Opt\n")
    w("set_option maxHeartbeats 4000000")
    w("set_option linter.unusedSimpArgs false\n")
    w(f"/-- Isolating interval for `u₀`, width `10^-{DIGITS}`. -/")
    w(f"def lo : ℚ := {ratQ(lo)}")
    w(f"def hi : ℚ := {ratQ(hi)}\n")
    w("lemma u₀_bounds : (lo : ℝ) ≤ u₀ ∧ u₀ ≤ hi := by")
    w("  have h := u₀_mem_of_sign (lo := (lo : ℝ)) (hi := (hi : ℝ))")
    w("    (by norm_num [lo]) (by norm_num [hi]) (by norm_num [lo, hi]) (by norm_num [P, lo]) (by norm_num [P, hi])")
    w("  exact ⟨h.1.le, h.2.le⟩\n")
    w("lemma P_u₀' : 5*u₀^8 - 10*u₀^7 - 2*u₀^6 + 14*u₀^5 + 12*u₀^4 - 6*u₀^3 + 2*u₀^2 + 2*u₀ - 1 = 0 :=")
    w("  P_u₀\n")

    one = const(1)
    u = [F(0), F(1)]
    opu2 = add(one, mul(u, u))
    D = sub(add(one, mul(const(2), u)), mul(u, u))

    def quot(E):
        q, r = divmod_(E, P)
        assert r == [], r
        return q

    w(f"/-- `cos θ = (1 − u₀²)/(1 + u₀²)` in the power basis. -/")
    w(f"noncomputable def cA : ℝ := pe {plist(c)} u₀")
    w(f"noncomputable def sA : ℝ := pe {plist(s)} u₀")
    w(f"noncomputable def TA : ℝ := pe {plist(T)} u₀\n")
    k = quot(sub(sub(one, mul(u, u)), mul(c, opu2)))
    w("lemma cos_a : Real.cos a = cA := by")
    w("  rw [a, cos_two_arctan, div_eq_iff (by positivity)]")
    w("  simp only [cA, pe, List.foldr]")
    w(f"  linear_combination {pexpr(k)} * P_u₀'\n")
    k = quot(sub(mul(const(2), u), mul(s, opu2)))
    w("lemma sin_a : Real.sin a = sA := by")
    w("  rw [a, sin_two_arctan, div_eq_iff (by positivity)]")
    w("  simp only [sA, pe, List.foldr]")
    w(f"  linear_combination {pexpr(k)} * P_u₀'\n")
    k = quot(sub(add(mul(const(6), u), const(4)), mul(T, D)))
    w("lemma D_pos : 0 < 1 + 2 * u₀ - u₀ ^ 2 := by")
    w("  have := u₀_spec.1; nlinarith [this.1, this.2]\n")
    w("lemma T_eq : T = TA := by")
    w("  rw [T, div_eq_iff D_pos.ne']")
    w("  simp only [TA, pe, List.foldr]")
    w(f"  linear_combination {pexpr(k)} * P_u₀'\n")

    lemmas = []

    def fact(name, stmt, pre, E, strict=False):
        """E = R - L as an unreduced polynomial; prove `stmt` after `pre` tactics."""
        q, r = divmod_(E, P)
        lines = [f"lemma {name} : {stmt} := by"]
        if r:
            lb, _ = horner_iv(r, lo, hi)
            assert lb > 0 if strict else lb >= 0, (name, float(lb))
            fn = "peQ_pos_of_hIv" if strict else "peQ_nonneg_of_hIv"
            lines.append(f"  have hr := {fn} lo hi u₀ u₀_bounds.1 u₀_bounds.2 {qlist(r)} (by decide +kernel)")
            lines.append("  simp only [peQ_cons, peQ_nil] at hr; push_cast at hr")
        else:
            assert not strict
        lines += ["  " + t for t in pre]
        # for an inequality goal `L ≤ R`, `linear_combination` matches `L - R` against the
        # combination's `lhs - rhs`, so the equation `P(u₀) = 0` enters with coefficient `-q`
        comb = ("hr" if r else "0") + (f" - {pexpr(q)} * P_u₀'" if q else "")
        lines.append("  linear_combination " + comb)
        w("\n".join(lines) + "\n")
        lemmas.append(name)
        return r == []

    # positivity of cos a, sin a (for wid a)
    fact("cA_pos", "0 < cA", ["simp only [cA, pe, List.foldr]"], c, strict=True)
    fact("sA_pos", "0 < sA", ["simp only [sA, pe, List.foldr]"], s, strict=True)
    w("lemma wid_a : wid a = cA + sA := by")
    w("  rw [wid, cos_a, sin_a, abs_of_pos cA_pos, abs_of_pos sA_pos]\n")
    fact("T_lt_U", "T < 387708359002281417731 / 10 ^ 20",
         ["rw [T_eq]", "simp only [TA, pe, List.foldr]"],
         sub(const(F(387708359002281417731, 10 ** 20)), T), strict=True)

    # centres
    for i, ((X, Y), t) in enumerate(sqs):
        w(f"noncomputable def x{i} : ℝ := pe {plist(X)} u₀")
        w(f"noncomputable def y{i} : ℝ := pe {plist(Y)} u₀")
    w("")
    w("/-- Centres of Trump's packing. -/")
    w("noncomputable def ctr : Fin 11 → ℝ × ℝ := ![" +
      ", ".join(f"(x{i}, y{i})" for i in range(11)) + "]")
    w("/-- Angles: six axis-parallel squares, five tilted by `a`. -/")
    w("noncomputable def ang : Fin 11 → ℝ := ![" +
      ", ".join("0" if t == 0 else "a" for (_, t) in sqs) + "]\n")

    ALL = "cA, sA, TA, " + ", ".join(f"x{i}, y{i}" for i in range(11)) + ", pe, List.foldr"
    WSIMP = ("simp only [wid_sub_add_pi_div_two, wid_sub_add_pi, wid_sub_sub_pi_div_two, wid_sub_pi_div_two, "
             "wid_sub_pi, sub_neg_eq_add, wid_add_pi_div_two, wid_add_pi, sub_self, sub_zero, zero_sub, wid_neg', wid_zero, "
             "wid_pi_div_two, wid_pi, wid_a, Real.cos_add_pi_div_two, Real.sin_add_pi_div_two, Real.cos_add_pi, "
             "Real.sin_add_pi, Real.cos_sub_pi_div_two, Real.sin_sub_pi_div_two, Real.cos_zero, Real.sin_zero, "
             "Real.cos_pi_div_two, Real.sin_pi_div_two, Real.cos_pi, Real.sin_pi, Real.cos_neg, Real.sin_neg, "
             "cos_a, sin_a, T_eq]")

    # walls
    contacts = 0
    for i, ((X, Y), t) in enumerate(sqs):
        wv = one if t == 0 else add(c, s)
        half = [x / 2 for x in wv]
        th = "0" if t == 0 else "a"
        parts = [
            (f"wid {th} / 2 ≤ x{i}", sub(X, half)),
            (f"x{i} ≤ T - wid {th} / 2", sub(sub(T, half), X)),
            (f"wid {th} / 2 ≤ y{i}", sub(Y, half)),
            (f"y{i} ≤ T - wid {th} / 2", sub(sub(T, half), Y)),
        ]
        for k_, (st, E) in enumerate(parts):
            contacts += fact(f"wall{i}_{k_}", st, [WSIMP, f"simp only [{ALL}]"], E)
        w(f"lemma adm{i} : Adm T (x{i}, y{i}) {th} := ⟨wall{i}_0, wall{i}_1, wall{i}_2, wall{i}_3⟩\n")

    # pairs
    cs = {0: {'cos': one, 'sin': []}, 'a': {'cos': c, 'sin': s}}
    dirs = []
    for psi in (0, 'a'):
        C0, S0 = cs[psi]['cos'], cs[psi]['sin']
        base = "0" if psi == 0 else "a"
        # φ, (cos φ, sin φ)
        if psi == 0:
            dirs += [("0", 0, one, []), ("Real.pi / 2", 0, [], one), ("Real.pi", 0, const(-1), []),
                     ("-(Real.pi / 2)", 0, [], const(-1))]
        else:
            dirs += [("a", 'a', c, s), ("a + Real.pi / 2", 'a', [F(-x) for x in s], c),
                     ("a + Real.pi", 'a', [F(-x) for x in c], [F(-x) for x in s]),
                     ("a - Real.pi / 2", 'a', s, [F(-x) for x in c])]
    pair_contacts = 0
    for i in range(11):
        for j in range(i + 1, 11):
            (Xi, Yi), ti = sqs[i]
            (Xj, Yj), tj = sqs[j]
            best = None
            for (phi, fam, cph, sph) in dirs:
                wi = one if ti == fam else add(c, s)
                wj = one if tj == fam else add(c, s)
                Rr = add(mul(cph, sub(Xj, Xi)), mul(sph, sub(Yj, Yi)))
                E = sub(Rr, [x / 2 for x in add(wi, wj)])
                r = red(E)
                val = ev(r, (lo + hi) / 2) if r else F(0)
                if best is None or val > best[0]:
                    best = (val, phi, E)
            val, phi, E = best
            thi = "0" if ti == 0 else "a"
            thj = "0" if tj == 0 else "a"
            st = f"Disjoint (sqInt (x{i}, y{i}) {thi} 1) (sqInt (x{j}, y{j}) {thj} 1)"
            pair_contacts += fact(f"pair{i}_{j}", st,
                                  [f"apply disjoint_of_dir ({phi})", WSIMP, f"simp only [{ALL}]"], E)
    w("end SquarePacking.S11Opt")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"walls: 44 facts, {contacts} contacts; pairs: 55, {pair_contacts} contacts", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1])
