import Sqpack.S11Opt.Data

/-!
# `s(11) ≤ T ≈ 3.8770835900`, kernel-checked

Trump's packing (1979) of 11 unit squares in `[0, T]²`: six axis-parallel squares and five tilted
by `θ = 2·arctan u₀`, with `u₀` the unique root of `P` in `(9/25, 37/100)` and
`T = (6u₀ + 4)/(1 + 2u₀ − u₀²)`.  Every coordinate is a polynomial of degree `≤ 7` in `u₀`
(`Sqpack/S11Opt/Data.lean`, generated by `scripts/s11opt/gen.py`).  Containment is the
admissibility test `sq_subset_box_iff` (44 inequalities, 11 of them tight); disjointness is the
separating-axis test `disjoint_of_dir` along an edge normal (55 pairs, 14 of them in contact).
Each inequality is an exact polynomial identity modulo `P` plus a sign of the remainder on an
isolating interval of width `10⁻⁴⁰`, checked by the kernel (`hIv`).
-/

namespace SquarePacking.S11Opt

/-- **Trump's packing**: `11` unit squares fit in the square of side `T`. -/
theorem packs_T : Packs 11 T := by
  refine ⟨ctr, ang, fun i => ?_, fun i j hij => ?_⟩
  · rw [sq_subset_box_iff]
    fin_cases i
    exacts [adm0, adm1, adm2, adm3, adm4, adm5, adm6, adm7, adm8, adm9, adm10]
  · fin_cases i <;> fin_cases j
    · exact absurd rfl hij
    · exact pair0_1
    · exact pair0_2
    · exact pair0_3
    · exact pair0_4
    · exact pair0_5
    · exact pair0_6
    · exact pair0_7
    · exact pair0_8
    · exact pair0_9
    · exact pair0_10
    · exact (pair0_1).symm
    · exact absurd rfl hij
    · exact pair1_2
    · exact pair1_3
    · exact pair1_4
    · exact pair1_5
    · exact pair1_6
    · exact pair1_7
    · exact pair1_8
    · exact pair1_9
    · exact pair1_10
    · exact (pair0_2).symm
    · exact (pair1_2).symm
    · exact absurd rfl hij
    · exact pair2_3
    · exact pair2_4
    · exact pair2_5
    · exact pair2_6
    · exact pair2_7
    · exact pair2_8
    · exact pair2_9
    · exact pair2_10
    · exact (pair0_3).symm
    · exact (pair1_3).symm
    · exact (pair2_3).symm
    · exact absurd rfl hij
    · exact pair3_4
    · exact pair3_5
    · exact pair3_6
    · exact pair3_7
    · exact pair3_8
    · exact pair3_9
    · exact pair3_10
    · exact (pair0_4).symm
    · exact (pair1_4).symm
    · exact (pair2_4).symm
    · exact (pair3_4).symm
    · exact absurd rfl hij
    · exact pair4_5
    · exact pair4_6
    · exact pair4_7
    · exact pair4_8
    · exact pair4_9
    · exact pair4_10
    · exact (pair0_5).symm
    · exact (pair1_5).symm
    · exact (pair2_5).symm
    · exact (pair3_5).symm
    · exact (pair4_5).symm
    · exact absurd rfl hij
    · exact pair5_6
    · exact pair5_7
    · exact pair5_8
    · exact pair5_9
    · exact pair5_10
    · exact (pair0_6).symm
    · exact (pair1_6).symm
    · exact (pair2_6).symm
    · exact (pair3_6).symm
    · exact (pair4_6).symm
    · exact (pair5_6).symm
    · exact absurd rfl hij
    · exact pair6_7
    · exact pair6_8
    · exact pair6_9
    · exact pair6_10
    · exact (pair0_7).symm
    · exact (pair1_7).symm
    · exact (pair2_7).symm
    · exact (pair3_7).symm
    · exact (pair4_7).symm
    · exact (pair5_7).symm
    · exact (pair6_7).symm
    · exact absurd rfl hij
    · exact pair7_8
    · exact pair7_9
    · exact pair7_10
    · exact (pair0_8).symm
    · exact (pair1_8).symm
    · exact (pair2_8).symm
    · exact (pair3_8).symm
    · exact (pair4_8).symm
    · exact (pair5_8).symm
    · exact (pair6_8).symm
    · exact (pair7_8).symm
    · exact absurd rfl hij
    · exact pair8_9
    · exact pair8_10
    · exact (pair0_9).symm
    · exact (pair1_9).symm
    · exact (pair2_9).symm
    · exact (pair3_9).symm
    · exact (pair4_9).symm
    · exact (pair5_9).symm
    · exact (pair6_9).symm
    · exact (pair7_9).symm
    · exact (pair8_9).symm
    · exact absurd rfl hij
    · exact pair9_10
    · exact (pair0_10).symm
    · exact (pair1_10).symm
    · exact (pair2_10).symm
    · exact (pair3_10).symm
    · exact (pair4_10).symm
    · exact (pair5_10).symm
    · exact (pair6_10).symm
    · exact (pair7_10).symm
    · exact (pair8_10).symm
    · exact (pair9_10).symm
    · exact absurd rfl hij

/-- A packing needs a container of side at least `1`. -/
lemma one_le_of_packs {n : ℕ} (hn : 0 < n) {s : ℝ} (h : Packs n s) : 1 ≤ s := by
  obtain ⟨ctr, ang, hin, -⟩ := h
  obtain ⟨h1, h2, -, -⟩ := (sq_subset_box_iff s _ _).mp (hin ⟨0, hn⟩)
  linarith [one_le_wid (ang ⟨0, hn⟩)]

/-- **`s(11) ≤ T`.** -/
theorem minSide_le_T : minSide 11 ≤ T :=
  csInf_le ⟨0, fun _ hs => by linarith [one_le_of_packs (by norm_num) hs]⟩ packs_T

/-- The numeric form: `s(11) < 3.87708359002281417731`. -/
theorem minSide_lt_U : minSide 11 < 387708359002281417731 / 10 ^ 20 :=
  lt_of_le_of_lt minSide_le_T T_lt_U

end SquarePacking.S11Opt
